spring.application.name=bidmart-catalogue-service

server.port=8080

# Konfigurasi Database H2 (In-Memory)
spring.datasource.url=jdbc:h2:mem:bidmart_catalogue
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Agar Hibernate otomatis membuat tabel di H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Agar Flyway tidak error saat pakai H2
spring.flyway.enabled=false