spring.application.name=bidmart-catalogue-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/bidmart_catalogue
spring.datasource.username=postgres
spring.datasource.password=Jovanus_2106

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true